export enum ENUM_PAGE {
  DASHBOARD = "/dashboard",
  JODS = "/jobs",
  MACHINE = "/machine",
  REPORTS = "/report",
  REPORT_OVERVIEW = "/report/overview",
  REPORT_SALES = "/report/sales",
  REPORT_SALES_BY_MACHINE = "/report/sales/machines",
  REPORT_SALES_BY_PRODUCT = "/report/sales/products",
  REPORT_SALES_BY_PAYMENT = "/report/sales/payments",
  REPORT_INVENTORY = "/report/inventory",
  REPORT_DETAILED = "/report/detailed",
  HISTORY = "/history",
  ADMIN = "/admin",
  PRODUCT = "/product",
  LOGIN = "/login",
}
